### ISSUE TITLE
Review Writer Chapter 7 (AOO41WG7-Working with styles)

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#106]
**Review of AOO41WG7**

**Comment by FJCC** [comment]
Hi Keith,
I'll review the new versions of chapters 5 - 7 unless Michele wants to work
on one or more of them. I just sent her a message to check with her.
Regards,
Francis

**Comment by knmc** [comment]
Add to new project to track as backlog

**Comment by FJCC** [comment]
Edited by FJCC and Michele
