### ISSUE TITLE
3rd review of AOO41WG9

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#109]
A 3rd review of AOO41WG9 is needed.

**Comment by FJCC** [comment]
Keith - It looks to me like all the headers on pages 1-8 have been converted to title case but not the headings from page 9 onward. I will convert the headings on the later pages to title case but I want to give you a chance to correct me if you intentionally didn't change them.

**Comment by knmc** [comment]
Francis—You may have the wrong version of the file. I just checked mine, and all were done except one which I will change now and commit.

**Comment by FJCC** [comment]
OK, I'll fetch the repository a little later today.

**Comment by FJCC** [comment]
Keith - I think I got this straightened out. I did have a partially edited version of AOO41WG9 and I had committed some changes to that. I reverted that commit, fetched the latest version of the Writer Guide, merged that locally, and pushed back to the main repository.  I'll proceed with editing WG9.

**Comment by FJCC** [comment]
Michele and FJCC reviewed AOO41WG9.  The chapter name in the footers differs on odd and even pages but I'm not sure what the preferred content is.
