### ISSUE TITLE
Ready for 3rd Review

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#114]
Chapter 11 of the Apache OpenOffice® Writer is ready for 3<sup>rd</sup> review

**Comment by FJCC** [comment]
FJCC and Michele reviewed the chapter. It needs another review because there are extensive changes to the section Using the Mail Merge Wizard to Create a Form Letter. The main changes are near the beginning of the section and in the sub-section Create Salutation. 
Closing this round of the review.
