### ISSUE TITLE
Review AOOWG4111, 4th review

### ISSUE THREAD

**Issue by FJCC** [apache/openoffice-docs#124]
The 3rd review resulted in extensive changes to the section Using the Mail Merge Wizard to Create a Form Letter. The main changes are near the beginning of the section and in the sub-section Create Salutation. The previous text overstated the limitations of the Mail Merge Wizard.
We also replaced the column name Sex with Gender in the example data to match current usage. This required replacing several figures in addition to changes in the text.

**Comment by knmc** [comment]
This review was completed, and other changes were made.
