### ISSUE TITLE
AOO41WG10 Ready for 3rd Review

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#126]
3rd Review of AOO41WG10 needed.

**Comment by FJCC** [comment]
I think we have gotten tangled up here. Issue 118, which is closed, was opened on 2023-12-18 and it was a review of chapter 10. There are then commits on the 18th and the 20th after I and Michele accepted Keith's changes and made some more edits. Here is the git log of those.

> commit 5336d2149344969cb119cf17a31ac779388b3629
> Author: Francis <fjcc.apache@gmail.com>
> Date:   Wed Dec 20 16:16:12 2023 -0700
> 
>     AOO41WG410...odt Edited by Michele, reviewed by FJCC
> 
> commit 7bc935b0bbd0b857991cee6c7a16e86ccd8f1aeb
> Author: Francis <fjcc.apache@gmail.com>
> Date:   Mon Dec 18 15:59:08 2023 -0700
> 
>     AOO41WG410...odt accept Keith's edits + a few corrections

The latest commit, ba4a1b3, seems to have the version of chapter 10 that went into issue 118. If Keith can confirm that a mistake has been made, I can make a new commit with the version of chapter 10 that came out of issue 118, with Michele's edits.

**Comment by FJCC** [comment]
Committed (47a3957) the version of chapter 10 that was in 5336d21. The version of chapter 10 that was in the repository to trigger this issue was down level.
