### ISSUE TITLE
AOO41CG01 Ready for Next Revies.

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#137]

**Comment by FJCC** [comment]
Keith - since you found several instances of the wrong paragraph style in text preceding a list, I think I should go through the other chapters and fix that error. Let me know if you agree and that you will hold off on editing other chapters so we don't end up with conflicting edits.

**Comment by FJCC** [comment]
I am closing this issue because my editing of CG chapter 1 is done in commit 528770c.
