### ISSUE TITLE
Reviewing/Editing AOO41CG01-IntroducingCalc.odt

### ISSUE THREAD

**Issue by MackMike** [apache/openoffice-docs#154]
This is just an FYI that I'm currently reviewing and making edits to [AOO41CG01-IntroducingCalc.odt](https://github.com/apache/openoffice-docs/blob/Calc-Guide/Review/AOO41CG01-IntroducingCalc.odt) and will submit the edited document early next week.

**Comment by knmc** [comment]
Closed.  Should have been closed a long time ago.
