### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#2]
Testing of issues and projects

**Comment by orcmid** [comment]
I confirm that Issues is working here, and that it works for me as a watcher and not a registered contributor.

**Comment by orcmid** [comment]
I confirm that Projects is setup and there is a project board around updates, reviews, and review status.  I have not used Projects myself.  I suspect as this one is used and there are entries, we will know much more.

**Comment by knmc** [comment]
Thank you. for the confirmation Dennis. There seems to be an issue with the project board right now, in that It is not picking up one issue's. The entry you saw was the standard first entry in when a  Kanban Board was created.
