### ISSUE TITLE
Start Review of AOO41GS2.odt

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#27]
Start of  edit/review cycle for publication

**Comment by DiGro** [comment]
Keith,

I somehow missed this one. I've reviewed the file also. I pulled it from FJCC's repo, so that is probably a more recent version
I've made a PR (#32) with the file as a ZIP because it wasn't accepted as .odt
Sorry, will check Issues next time

**Comment by FJCC** [comment]
I have integrated DiGro's edits into AOO41GS2.odt.  I also used the text from http://www.openoffice.org/download/common/java.html to describe the Java requirements:
"The current versions of Apache OpenOffice work reliably with a variety of JREs including Oracle Java, versions 6, 7 and 8, openJDK, versions 6, 7 and 8 and AdoptOpenJDK, versions 8 and 11." Is that up to date? I added "You should use the most recent version of whichever JRE you choose for the best security and reliability."

**Comment by knmc** [comment]
Reviewed and Published
