### ISSUE TITLE
Start update of AOO41GS8.odt

### ISSUE THREAD

**Issue by FJCC** [apache/openoffice-docs#28]
This will be a major rewrite of the chapter on Base. I want to simplify the data in the examples, put more emphasis on database structure vs. the appearance of forms and reports, and fix a couple of important errors/omissions.

**Comment by knmc** [comment]
Assaigned Francis to the issue.

**Comment by FJCC** [comment]
A template has been applied and the formatting cleaned up but due to the extensive rewriting, more proofreading is needed. That is my next task.

**Comment by knmc** [comment]
Final copy editing done and ready to publish
