### ISSUE TITLE
Change text color to brand color ?

### ISSUE THREAD

**Issue by DiGro** [apache/openoffice-docs#31]
Should we change some text color(s) ??

Should we use another color for the blue headings, for now it is Diagram 12 
which is RGB 0,132,209

Default brand color for AOO is RGB 14,133,205  (https://wiki.openoffice.org/wiki/Brand_Colors)

Diagram 12:
![Kleur Diagram 12](https://user-images.githubusercontent.com/5002095/111911574-750cc300-8a66-11eb-8495-45ad858ea480.png)

AOO blue:
![Kleur AOO blue](https://user-images.githubusercontent.com/5002095/111911580-79d17700-8a66-11eb-8982-5c59986072a0.png)

We may now still be in the position to change the color in the template before we publish anything

**Comment by knmc** [comment]
DiGro. That sounds great to do. I will change the template later today.

**Comment by knmc** [comment]
File AOOdoc.ott Created with new color AOO blue add pushed to  Templates branch
