### ISSUE TITLE
2nd review of AOO41GS4

### ISSUE THREAD

**Issue by DiGro** [apache/openoffice-docs#36]
Reviewed the file AOO41GS4 from the Getting Started folder

Adapted three images (1 mentioned OpenOffice.org graphics56); one (graphic70) had the obsolete logo of ODF authors and graphics77 was somehow blurred on the top side)

Changes are recorded
Changed several > to → in menu options
changed one LibreOffice note to AOO

File with changes is: AOO41GS4_digro_20210625.odt in Review folder

**Comment by knmc** [comment]
Ready to be published to Main

**Comment by knmc** [comment]
Closed
