### ISSUE TITLE
2nd review of the file AOO41GS5

### ISSUE THREAD

**Issue by DiGro** [apache/openoffice-docs#39]
2nd review of the file AOO41GS5 from the repository of Francis.

Some minor grammar and format changed/corrected.  Changes are ON

Changes in the  file AOO41GS5_digro_20210717 in the Review folder of Getting Started-guide

**Comment by FJCC** [comment]
The changes look good to me except that Figure 1 is linked to a file and cannot be displayed when I download the document. 
Sorry I responded rather slowly. I was on a short vacation.

**Comment by DiGro** [comment]
Deleted the link for the image. Should show now in download.
Turned off Changes and Grammar

Updated file is: AOO41GS5_digro_20210722.odt  attached

[AOO41GS5_digro_20210722.odt](https://github.com/apache/openoffice-docs/files/6861265/AOO41GS5_digro_20210722.odt)

**Comment by FJCC** [comment]
Yes, I see the image now. Thanks!

Francis

**Comment by knmc** [comment]
Issue closed and new file open for corrected file.
