### ISSUE TITLE
2nd review remaining files

### ISSUE THREAD

**Issue by DiGro** [apache/openoffice-docs#40]
Reviewed the remaining files of the Getting Started guide
Some smaller typo's corrected and adjusted some pictures

Changed files 
AOO41GS6_digro_20210909.odt
AOO41GS7_digro_20210909.odt
AOO41GS8_digro_20210409.odt
AOO41GS9_digro_20210909.odt
AOO41GS11_digro_20210909.odt
AOO41GS12_digro_20210909.odt
added to folder Review

**Comment by FJCC** [comment]
Thanks for checking all of those files, especially GS8 that needed so much work. When I downloaded AOO41GS8 I found that the Figure numbering breaks  at Figure 22. I see only the caption for Figure 22 and also the following figure. The figure after 22 is numbered as 43 and the one after that is numbered as 150. There are MANY Text Frames piled up at the locations for figures 22 and 43. I saw this kind of corrupt structure in an earlier version of this document. I will see if I can clean this up by editing the xml file.

**Comment by DiGro** [comment]
OK, thanks.
I will have a look to, to see if I can clean it up

**Comment by DiGro** [comment]
Uploaded fixed file AOO41GS8_digro_20210922_fixed.odt 
After examination the old file I saw that it was inserting excessive frames on saving.
Seemed to originate from inserted pictures.
Removed all pictures and added them again.
Had to renew some in the process.
After the new insertion all seems well. Please review this file instead of AOO41GS8_digro_20210409

**Comment by FJCC** [comment]
I checked AOO41GS8_digro_20210922_fixed.odt and found only three problems:
1. On page 16, the heading _Entering data with the new form_ has gotten merged with the following paragraph so that the heading formatting applies to both the heading and the paragraph.
2. Figure 24 on page 30 extends below the bottom margin of the page. Changing the anchor of the frame to As Character caused the figure to move to the next page on my system.
3. Figure 32 on page 36 also extends below the bottom margin of the page. I had to add a blank paragraph to push the figure to the next page.  I expect there is a better way to control this.

I also had trouble reviewing all of the edits. The menu Edit -> Changes -> Accept or Reject would bring up the first change but selecting another of the listed changes crashed OpenOffice every time I tried it.  If I applied a filter to the changes using the Filter tab on the Accept or Reject dialog, the crashing stopped. Removing the filter then allowed me to see all of the changes without crashing.  Do you see the same problem?

**Comment by DiGro** [comment]
Francis, I looked at the file again.

The first problem ( Heading on page 16 merging with next paragraph) is in the changes. I was waiting for the changes I made to be accepted/rejected to fix it later, if necessary.

Actually the fixes on the inserted pictures 24 and 32 should probably also be made after reviewing the changes.
I think it not  really makes sense to fix this and after that reviewing the changes to Accept or Reject. Better to do the fix afterwards, just my 2 cts..

Regarding the changes to Accept or Reject. All is working well on my machine ( Win10 with AOO 4.1.10). I can, without a problem, jump from the one change to the other. No filter applied. No crashing or problems at all.

I will make a another check after the changes I made are reviewed (Accepted or Rejected). Would that be an idea ??

**Comment by FJCC** [comment]
I would accept all of your changes. I cannot, as far as I know, push to the apache/openoffice-docs repository; I am not a committer. I am a novice git user, so please let me know if there is an easier or better route than you accepting your own changes based on this message and then proceeding with the next changes. 
There is also an additional chapter 13 titled Getting Started with Macros that I should get to you. I have to review its status.
The repository I forked a few months ago is now 42 commits behind the apache repository of the Getting Started branch and it includes that new chapter. I will try to get my fork up to date with the apache repo but I suspect I'll get into a tangle given my inexperience and the fact that we cannot do a Diff on these documents.

**Comment by orcmid** [comment]
The normal approach would be to create a personal branch of the repo to protect your changes.  Then, in whatever cloned upstream branch you are working in, do the Fetch Upstream operation.   This should walk you through any merge conflicts.

You might not need the personal branch you created for safety.  You could try merging it back in or simply copying the modified document you have to the updated clone.

This may be all too wonky.   

I agree about the choices of binary formats (and branches) that defeats the ordinary use of GitHub.

**However, you can submit a pull request** to the upstream open-office-docs repository (i.e., here).   When you are ready to submit the changed files you have made on the same branch as the project, just use the pull request operation in the GitHub menu when your GitHub openoffice-docs clone is open in your Browser.  It is pretty straightforward and doing it with only a single (or very few) changed file(s) should work.  Then the official contributors can review your request, give you feedback, figure out the merge, etc.  Not to worry.  You can't mess anything up.

I don't know of any necessity to be an Apache committer to operate this way.  That would completely defeat the value of using GitHub.

**Comment by DiGro** [comment]
@FJCC 

as orcmid said: it should be possible to make a Pull Request in apache/openoffice-docs to upload both files.

Regarding AOO41GS13-GettingStartedWithMacros.odt. I downloaded it from your repository just minutes ago.
It won't open on my machine. It starts opening but then hangs. It shows a small progress bar and then stops loading

**Comment by DiGro** [comment]
Uploaded the file AOO41GS8_digro_20210927_final_draft.odt after rechecking the reviewed file AOO41GS8_digro_20210922_fixed.odt by FJCC.

File is no longer adding excessive frames.
Changed some format
Applied format to heading
Separated merged heading and paragraph
Removed some excessive spaces
Pictures are in place

File should be OK now. However, it might have absorbed some format from an old OOo template on my machine.
Maybe that could be checked before publishing

**Comment by knmc** [comment]
Closed as completed.
