### ISSUE TITLE
The Getting Started Guide .gitattributes is named .gitignore incorrectly

### ISSUE THREAD

**Issue by orcmid** [apache/openoffice-docs#42]
The purpose of a `.gitattributes` file is to prevent treatment of binary files as text, corrupting them on movement to and from working folders.

Use of `.gitignore` is to exclude certain files and directories from the git altogether, even though they might appear in the working folders.  They will never be included in a commit and in extraction of the branch into a working folder set.

The formats are also different.  

Renaming that `.gitignore` that contains Git Attributes information to `.gitattributes` should achieve the intended effects.

**Comment by knmc** [comment]
The .gitignore file is now gone and the .gitattributes file should be correct. if you believe there is still a problem please reopen.
