### ISSUE TITLE
AOO41GS4.odt Missing Figure 26

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#45]
Figure 26 in AOO41GS4.odt is showing as a file \\ reference rather than an embedded reference 
(https://user-images.githubusercontent.com/66489645/163234649-e5da5c2f-ee04-448e-9dff-2b10a0c50929.png). @DiGro, I believe this was your last commit on this chapter.
[AOO41GS4.odt](https://github.com/apache/openoffice-docs/files/8483517/AOO41GS4.odt)

**Comment by DiGro** [comment]
Should be fixed now by removing the link to the image, which should embed the figure in the file.
Also noted that two other pictures did the same when I downloaded the file.
Noticed that links to the pictures I inserted (graphics56 (=Figure 11), graphics70 (= second from above picture on page 21) and graphics77(=Figure 26) were not removed (Edit --> Links)
Fixed file is attached to this message
[AOO41GS4_digro_20220414.odt](https://github.com/apache/openoffice-docs/files/8488859/AOO41GS4_digro_20220414.odt)
