### ISSUE TITLE
Publish AOO41GS via WikiPublisher

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#55]
Use the WikiPublisher to publish AOO41GS to mwiki as a wiki page.

**Comment by DiGro** [comment]
Started working on this. Assigned to me

**Comment by DiGro** [comment]
Completed. GS4 is published on the wiki: https://wiki.openoffice.org/wiki/Documentation/AOO4_User_Guides/Getting_Started

Issue closed
