### ISSUE TITLE
Publish AOO41GS PDF to mwiki

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#57]

**Comment by knmc** [comment]
Completed

**Comment by Pilot-Pirx** [comment]
Hi Keith,
Are Chapter 1 and 6 missing? And I see Chapter 2 twice...
And on page 123 it is "Open Office" instead of "OpenOffice"

**Comment by knmc** [comment]
Reopening to correct mistakes reported by Matthias

**Comment by knmc** [comment]
Problems reported by @Pilot-Pirx fixed

**Comment by DiGro** [comment]
Checked and repaired the files in ForWiki folder.
Reassembled a new .ODM file and subsequently a new PDF file from that.

Cab't upload those files here (.odm not supported and the new PDF is too big (93 MB)), but did upload the exported .ODT file from the .ODM. You cab make your own PDF by exporting the .ODT as PDF
[AOO41GS_fixed_20220614.odt](https://github.com/apache/openoffice-docs/files/8902160/AOO41GS_fixed_20220614.odt)
Please check if this is what we want. (I think it is ;-) )

**Comment by DiGro** [comment]
Just noticed that the .ODM file tries to updated the links yo the files which doesn't work on GitHub.
Added the .ODT file, exported from the .ODM, which should be readable and could be exported to PDF

[AOO41GS_fixed_20220614.odt](https://github.com/apache/openoffice-docs/files/8902673/AOO41GS_fixed_20220614.odt)

**Comment by knmc** [comment]
Dick, I updated  your latest commits and will check the PDF. Also, doing a Save As of the ODM as an ODT still creates an ODM formatted document, and will still want to update all the links. Plus, all the repositories should now have proper gitattribute files, which should make it unnecessary to have to change the names of files to commit them. If you are still having problems, please let me know, so we can get it fixed.

**Comment by knmc** [comment]
Still seeing formatting in the PDF file that should have been changed. Can you push all the changes you made in your ForWiki folder to GitHub?

**Comment by knmc** [comment]
Closing as stale
