### ISSUE TITLE
Review of complete Getting Started book (AOO41GS.odt

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#92]
The Getting Started Guide Complete book is finished and needs a thorough review. There were again many cross-references that were out of sequence and had to be changed manually. It requires a second set of eyes to make sure nothing was missed, and it is ready to publish.

**Comment by FJCC** [comment]
I will go through the document.

**Comment by FJCC** [comment]
I'd like to confirm that the document to be reviewed is [AOO41GS.odt](https://github.com/apache/openoffice-docs/blob/Getting-Sarted-Guide/Review/AOO41GS.odt), the one in the Review folder. Is that right? It seems obvious, but I don't want to review 300 pages of the wrong thing.

**Comment by knmc** [comment]
That is precisely the one to review Francis. Thank you for checking.

**Comment by FJCC** [comment]
Hi Keith,
I have reached chapter 9, Getting Started With Math, and found that all of
the Math objects are missing. They have been replaced with an icon of an
electrical plug and the text Object X, where X is a number. All of the
figures are there, only the Math objects are missing. Fortunately,
AOO41GS9.odt still has the Math objects.Did you make chapter 9 using copy
and paste from AOO41GS9.odt? I'd like to use the same process you used and
see if there is a reproducible problem. Do you remember anything unusual
happening with chapter 9?
Other than this problem, the review is going very smoothly. I made a few
corrections but I'm impressed with how few in such a long document.
Francis

**Comment by knmc** [comment]
This has been completed.
